apiVersion: template.openshift.io/v1
kind: Template
apiVersion: v1
metadata:
  name: nodejs-ubi8docker-route-template
  annotations:
    openshift.io/display-name: "nodejs-ubi8docker-route-template"
    description: >-
      The template for deployment Node.js service using ubi8docker
      approach

    tags: "node.js"
    iconClass: fas fa-tools
    openshift.io/provider-display-name: "Pavlo Shcherbukha" 
    openshift.io/documentation-url: "https://github.com/pavlo-shcherbukha/ubi8-nodejs-rdbg.git" 
    openshift.io/support-url: "https://github.com/pavlo-shcherbukha/ubi8-nodejs-rdbg.git" 
objects:
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: "${APP_NAME}"
        app.kubernetes.io/part-of: "${APP_NAME}"
      name: "${ROUTENAME}"
    spec:
      host: "${HOSTNAME}"
      port:
        targetPort: ${{PORTNUMBER}}
      to:
        kind: "Service"
        name: ${APP_SERVICE_NAME}
        weight: null
    status:
      ingress: null
parameters:
  - name: NAMESPACE
    displayName: Namespace 
    description: The Namespace where service must be deployed. 
    required: true   
  - name: APP_SERVICE_NAME
    displayName: APP Service Name 
    description: The name of the OpenShift Service exposed for the APP.
    required: true   
  - name: APP_NAME
    displayName: Application Name 
    description: The name of the OpenShift Application  for Groupe of Servoces.
    required: true 
  - name: ROUTENAME
    displayName: ROUTE name 
    description: Input ROUTENAME name 
    required: true   
  - name: HOSTNAME
    displayName: HOST name 
    description: Input HOSTNAME name 
    required: true 
  - name: PORTNUMBER
    displayName: PORT NUMBER 
    description: Input PORT number 
    required: true 

  